
  - id: "5ff3-6021-cc75"
    web:
      metaDescription: "Donec sit amet suscipit nisi. Praesent ut congue nisl. Fusce in orci urna. In tincidunt vestibulum placerat. Donec venenatis urna sed rutrum tincidunt. Cras por"
      metaTitle: "Data Security"
      metaLinkText: "Data Security"
      metaKeywords: null
      pathPart: null
      path: null
      sitemapPriority: -1
      canonicalTagMode: 1
      canonicalQueryParamWhitelist: null
      canonicalTagCustomValue: null
      parent: "/"
    meta:
      sort: 129
      listed: true
    data:
      content: "<p><span style=\"display:block;text-align:justify\">Donec sit amet suscipit nisi. Praesent ut congue nisl. Fusce in orci urna. In tincidunt vestibulum placerat. Donec venenatis urna sed rutrum tincidunt. Cras porta, enim in consectetur dapibus, odio felis euismod lectus, nec semper eros nisl eget lectus.</span></p>"
      image: "https://rndhrw0l.media.zestyio.com/service_1.jpg"
      title: "Data Security"
  - id: "3709-b6b4-22b1"
    web:
      metaDescription: "Sed euismod quam leo, id pellentesque eros dictum sed. Praesent faucibus luctus commodo. Morbi non sollicitudin sem. Aenean laoreet porttitor est, non sodales l"
      metaTitle: "Data Management"
      metaLinkText: "Data Management"
      metaKeywords: null
      pathPart: null
      path: null
      sitemapPriority: -1
      canonicalTagMode: 1
      canonicalQueryParamWhitelist: null
      canonicalTagCustomValue: null
      parent: "/"
    meta:
      sort: 128
      listed: true
    data:
      content: "<p><span style=\"display:block;text-align:justify\">Sed euismod quam leo, id pellentesque eros dictum sed. Praesent faucibus luctus commodo. Morbi non sollicitudin sem. Aenean laoreet porttitor est, non sodales ligula fringilla a. Vestibulum sit amet sem varius, rutrum lorem non, volutpat justo. Proin quis mattis nibh. Praesent pellentesque ullamcorper justo.</span></p>"
      image: "https://rndhrw0l.media.zestyio.com/service_3.jpg"
      title: "Data Management"
  - id: "63ae-1cb3-1867"
    web:
      metaDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et leo et ante imperdiet euismod. Quisque finibus sem in tincidunt vulputate. Curabitur tincidunt"
      metaTitle: "Web Development"
      metaLinkText: "Web Development"
      metaKeywords: null
      pathPart: null
      path: null
      sitemapPriority: -1
      canonicalTagMode: 1
      canonicalQueryParamWhitelist: null
      canonicalTagCustomValue: null
      parent: "/"
    meta:
      sort: 127
      listed: true
    data:
      content: "<p><span style=\"display:block;text-align:justify\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et leo et ante imperdiet euismod. Quisque finibus sem in tincidunt vulputate. Curabitur tincidunt nibh erat, a efficitur mi tempus eget. Nullam lorem nunc, euismod vel risus vel, vestibulum tristique ex. Donec faucibus lobortis tincidunt.</span></p>"
      image: "https://rndhrw0l.media.zestyio.com/service_2.jpg"
      title: "Web Development"
